"""
HTML export for session history.

Converted from TypeScript core/export-html/index.ts
"""
import json
from datetime import datetime
from pathlib import Path
from typing import Any, Optional, List
from dataclasses import dataclass


@dataclass
class HtmlExportConfig:
    """Configuration for HTML export."""
    output_path: Optional[str] = None
    theme_name: str = "default"
    include_metadata: bool = True
    collapse_tool_calls: bool = False


def export_session_to_html(
    session_manager: Any,
    agent_state: dict[str, Any],
    config: Optional[HtmlExportConfig] = None,
) -> str:
    """
    Export a session to HTML format.

    Args:
        session_manager: SessionManager instance
        agent_state: Agent state dict with messages
        config: Export configuration

    Returns:
        Path to the exported HTML file
    """
    config = config or HtmlExportConfig()

    # Get output path
    if config.output_path:
        output_path = Path(config.output_path)
    else:
        output_path = session_manager.get_session_file() or Path("session.html")
        if not str(output_path).endswith(".html"):
            output_path = output_path.parent / (output_path.stem + ".html")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Build HTML content
    html_content = _build_html(session_manager, agent_state, config)

    # Write to file
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    return str(output_path)


def _build_html(
    session_manager: Any,
    agent_state: dict[str, Any],
    config: HtmlExportConfig,
) -> str:
    """Build HTML content from session data."""
    messages = agent_state.get("messages", [])
    entries = session_manager.get_entries()

    # Get session info
    header = session_manager.get_header()
    session_id = header.id if header else "unknown"
    timestamp = header.timestamp if header else datetime.now().isoformat()
    cwd = header.cwd if header else "."

    # Build message HTML
    messages_html = _build_messages_html(messages, config)

    # Get stats
    stats = _calculate_stats(messages)

    # Apply theme
    if config.theme_name == "light":
        theme = _get_light_theme()
    else:
        theme = _get_default_theme()

    # Build final HTML
    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session {session_id}</title>
    <style>{theme["css"]}</style>
</head>
<body class="{theme["body_class"]}">
    <div class="container">
        <header class="header">
            <h1>Session: {session_id}</h1>
            <p class="metadata">
                <span class="timestamp">{timestamp}</span>
                <span class="cwd">{cwd}</span>
            </p>
        </header>

        <section class="stats">
            <h2>Session Statistics</h2>
            <div class="stat-grid">
                <div class="stat-item">
                    <span class="stat-label">User Messages</span>
                    <span class="stat-value">{stats["user_messages"]}</span>
                </div>
                <div class="stat-item">
                    <span class="stat-label">Assistant Messages</span>
                    <span class="stat-value">{stats["assistant_messages"]}</span>
                </div>
                <div class="stat-item">
                    <span class="stat-label">Tool Calls</span>
                    <span class="stat-value">{stats["tool_calls"]}</span>
                </div>
                <div class="stat-item">
                    <span class="stat-label">Total Tokens</span>
                    <span class="stat-value">{stats["total_tokens"]}</span>
                </div>
            </div>
        </section>

        <section class="messages">
            <h2>Conversation</h2>
            {messages_html}
        </section>

        <footer class="footer">
            <p>Generated by pi-coding</p>
        </footer>
    </div>
</body>
</html>"""

    return html


def _build_messages_html(messages: List[dict], config: HtmlExportConfig) -> str:
    """Build HTML for messages."""
    collapse_tool_calls = config.collapse_tool_calls
    messages_html = []

    for i, msg in enumerate(messages):
        role = msg.get("role", "")
        content = msg.get("content", "")

        if role == "user":
            messages_html.append(_build_user_message_html(content, i))
        elif role == "assistant":
            messages_html.append(_build_assistant_message_html(content, msg, i, collapse_tool_calls))
        elif role == "toolResult":
            messages_html.append(_build_tool_result_html(content, msg, i))
        elif role == "custom":
            messages_html.append(_build_custom_message_html(content, msg, i))

    return "\n".join(messages_html)


def _build_user_message_html(content: Any, index: int) -> str:
    """Build HTML for a user message."""
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        text = "\n".join(
            c.get("text", "")
            for c in content
            if isinstance(c, dict) and c.get("type") == "text"
        )
    else:
        text = str(content)

    escaped_text = _escape_html(text)

    return f"""<div class="message user-message">
            <div class="message-header">
                <span class="message-role">User</span>
                <span class="message-index">#{index + 1}</span>
            </div>
            <div class="message-content">
                <pre>{escaped_text}</pre>
            </div>
        </div>"""


def _build_assistant_message_html(
    content: Any,
    msg: dict,
    index: int,
    collapse_tool_calls: bool,
) -> str:
    """Build HTML for an assistant message."""
    text_parts = []
    tool_calls_html = []

    if isinstance(content, list):
        for block in content:
            if not isinstance(block, dict):
                continue

            block_type = block.get("type", "")

            if block_type == "text":
                text = block.get("text", "")
                if text:
                    # Format thinking blocks specially
                    if "thinking" in block_type.lower():
                        tool_calls_html.append(f'<div class="thinking-block">{_escape_html(text)}</div>')
                    else:
                        text_parts.append(text)

            elif block_type == "toolCall":
                tool_name = block.get("name", "")
                args = block.get("arguments", {})

                if collapse_tool_calls:
                    tool_calls_html.append(f'<details class="tool-call"><summary>{_escape_html(tool_name)}</summary><code>{_escape_html(_format_args(args))}</code></details>')
                else:
                    tool_calls_html.append(f'<div class="tool-call"><span class="tool-name">{_escape_html(tool_name)}</span><code>{_escape_html(_format_args(args))}</code></div>')

            elif block_type == "toolResult":
                result = block.get("text", "")
                is_error = block.get("isError", False)
                status_class = "tool-result-error" if is_error else "tool-result-success"
                tool_calls_html.append(f'<div class="tool-result {status_class}">{_escape_html(result)}</div>')

    # Combine text and tool calls
    content_html = ""
    if text_parts:
        escaped_text = _escape_html("\n".join(text_parts))
        content_html = f'<div class="message-content">{_markdown_to_html(escaped_text)}</div>'

    if tool_calls_html:
        tool_html = "\n".join(tool_calls_html)
        content_html += f'<div class="tool-calls">{tool_html}</div>'

    return f"""<div class="message assistant-message">
            <div class="message-header">
                <span class="message-role">Assistant</span>
                <span class="message-index">#{index + 1}</span>
            </div>
            {content_html}
        </div>"""


def _build_tool_result_html(content: Any, msg: dict, index: int) -> str:
    """Build HTML for a tool result message."""
    if isinstance(content, list):
        text = "\n".join(
            c.get("text", "")
            for c in content
            if isinstance(c, dict) and c.get("type") == "text"
        )
    elif isinstance(content, str):
        text = content
    else:
        text = str(content)

    is_error = msg.get("isError", False)
    status_class = "tool-result-error" if is_error else "tool-result-success"

    return f"""<div class="message tool-result-message">
            <div class="message-header">
                <span class="message-role">Tool Result</span>
                <span class="message-index">#{index + 1}</span>
            </div>
            <div class="message-content">
                <pre class="{status_class}">{_escape_html(text)}</pre>
            </div>
        </div>"""


def _build_custom_message_html(content: Any, msg: dict, index: int) -> str:
    """Build HTML for a custom message."""
    custom_type = msg.get("customType", "custom")
    display = msg.get("display", "")
    details = msg.get("details", {})

    content_str = str(content)
    escaped_content = _escape_html(content_str)

    return f"""<div class="message custom-message" data-type="{_escape_html(custom_type)}">
            <div class="message-header">
                <span class="message-role">{display or custom_type}</span>
                <span class="message-index">#{index + 1}</span>
            </div>
            <div class="message-content">
                <pre>{escaped_content}</pre>
                {f'<div class="message-details">{_escape_html(str(details))}</div>' if details else ''}
            </div>
        </div>"""


def _calculate_stats(messages: List[dict]) -> dict[str, int]:
    """Calculate session statistics."""
    user_messages = sum(1 for m in messages if m.get("role") == "user")
    assistant_messages = sum(1 for m in messages if m.get("role") == "assistant")
    tool_calls = 0
    total_tokens = 0

    for msg in messages:
        if msg.get("role") == "assistant":
            content = msg.get("content", [])
            if isinstance(content, list):
                tool_calls += sum(1 for c in content if c.get("type") == "toolCall")

            usage = msg.get("usage", {})
            total_tokens += usage.get("input", 0) + usage.get("output", 0)

    return {
        "user_messages": user_messages,
        "assistant_messages": assistant_messages,
        "tool_calls": tool_calls,
        "total_tokens": total_tokens,
    }


def _escape_html(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#39;")
    )


def _format_args(args: dict) -> str:
    """Format function arguments as string."""
    if not args:
        return ""

    formatted = []
    for key, value in args.items():
        if isinstance(value, str):
            formatted.append(f'{key}="{value}"')
        elif isinstance(value, (int, float, bool)):
            formatted.append(f'{key}={value}')
        else:
            formatted.append(f'{key}={repr(value)}')

    return " ".join(formatted)


def _markdown_to_html(text: str) -> str:
    """Convert markdown-style text to HTML."""
    # Simple markdown to HTML conversion
    html = text

    # Code blocks
    html = html.replace("```", "<code>").replace("```", "</code>")

    # Inline code
    import re
    html = re.sub(r'`([^`]+?)`', r'<code>\1</code>', html)

    # Bold
    html = re.sub(r'\*\*([^*]+?)\*\*', r'<strong>\1</strong>', html)

    # Italic
    html = re.sub(r'\*([^*]+)\*', r'<em>\1</em>', html)

    # Headers
    for level in range(1, 7):
        html = re.sub(
            rf'^{"#" * level}\s+(.+)$',
            rf'<h{level}>\1</h{level}>',
            html,
            flags=re.MULTILINE,
        )

    # Links
    html = re.sub(
        r'\[([^\]]+)\]\(([^\)]+)\)',
        r'<a href="\2">\1</a>',
        html,
    )

    # Line breaks
    html = html.replace("\n\n", "</p><p>")
    html = html.replace("\n", "<br>")

    return f"<p>{html}</p>"


def _get_default_theme() -> dict:
    """Get the default CSS theme."""
    return {
        "css": """
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    line-height: 1.6;
    max-width: 900px;
    margin: 0 auto;
    padding: 20px;
    background: #1e1e1e;
    color: #e0e0e0;
}

.container {
    background: #252525;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
}

.header {
    border-bottom: 1px solid #444;
    margin-bottom: 20px;
    padding-bottom: 20px;
}

.header h1 {
    margin: 0 0 10px 0;
    font-size: 1.5em;
}

.metadata {
    display: flex;
    gap: 20px;
    color: #888;
    font-size: 0.9em;
}

h2 {
    font-size: 1.2em;
    margin: 20px 0 10px 0;
    color: #fff;
    border-bottom: 1px solid #444;
    padding-bottom: 10px;
}

.stat-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 15px;
    margin: 20px 0;
}

.stat-item {
    background: #2a2a2a;
    padding: 10px 15px;
    border-radius: 4px;
    text-align: center;
}

.stat-label {
    display: block;
    font-size: 0.8em;
    color: #888;
    margin-bottom: 5px;
}

.stat-value {
    display: block;
    font-size: 1.2em;
    font-weight: 600;
    color: #4ec9b0;
}

.message {
    margin: 15px 0;
    padding: 15px;
    border-radius: 6px;
    border-left: 3px solid #444;
}

.user-message {
    background: #1a1a1a;
    border-left-color: #4ec9b0;
}

.assistant-message {
    background: #252525;
    border-left-color: #9b59b6;
}

.tool-result-message {
    background: #1e1e1e;
    border-left-color: #e74c3c;
}

.custom-message {
    background: #1a1a2a;
    border-left-color: #3498db;
}

.message-header {
    display: flex;
    justify-content: space-between;
    margin-bottom: 10px;
    font-size: 0.85em;
    color: #888;
}

.message-role {
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.user-message .message-role { color: #4ec9b0; }
.assistant-message .message-role { color: #9b59b6; }
.tool-result-message .message-role { color: #e74c3c; }
.custom-message .message-role { color: #3498db; }

.message-content {
    color: #ccc;
}

.message-content pre {
    background: #0d0d0d;
    padding: 10px;
    border-radius: 4px;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}

.tool-result-error {
    color: #e74c3c;
}

.tool-result-success {
    color: #2ecc71;
}

.thinking-block {
    background: #2a2a2a;
    padding: 10px;
    border-radius: 4px;
    margin: 10px 0;
    font-style: italic;
    color: #888;
}

.tool-calls {
    margin: 10px 0;
}

.tool-call code {
    background: #0d0d0d;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.9em;
}

.tool-name {
    color: #9b59b6;
}

details.tool-call {
    margin: 5px 0;
    background: #1a1a1a;
    border-radius: 4px;
    overflow: hidden;
}

details.tool-call summary {
    cursor: pointer;
    padding: 5px 10px;
    user-select: none;
}

details.tool-call summary:hover {
    background: #252525;
}

.tool-result {
    margin: 5px 0;
    padding: 8px 12px;
    border-radius: 4px;
}

.footer {
    margin-top: 30px;
    padding-top: 20px;
    border-top: 1px solid #444;
    text-align: center;
    color: #666;
    font-size: 0.85em;
}

code {
    font-family: 'Fira Code', 'Consolas', 'Monaco', 'Courier New', monospace;
    background: #0d0d0d;
    padding: 2px 6px;
    border-radius: 3px;
}

pre {
    font-family: 'Fira Code', 'Consolas', 'Monaco', 'Courier New', monospace;
}

a {
    color: #3498db;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
""",
        "body_class": "",
    }


def _get_light_theme() -> dict:
    """Get the light CSS theme."""
    return {
        "css": """
body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    line-height: 1.6;
    max-width: 900px;
    margin: 0 auto;
    padding: 20px;
    background: #ffffff;
    color: #333333;
}

.container {
    background: #f5f5f5;
    border-radius: 8px;
    padding: 20px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
}

.header {
    border-bottom: 1px solid #ddd;
    margin-bottom: 20px;
    padding-bottom: 20px;
}

.header h1 {
    margin: 0 0 10px 0;
    font-size: 1.5em;
}

.metadata {
    display: flex;
    gap: 20px;
    color: #666;
    font-size: 0.9em;
}

h2 {
    font-size: 1.2em;
    margin: 20px 0 10px 0;
    color: #333;
    border-bottom: 1px solid #ddd;
    padding-bottom: 10px;
}

.stat-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 15px;
    margin: 20px 0;
}

.stat-item {
    background: #ffffff;
    padding: 10px 15px;
    border-radius: 4px;
    text-align: center;
    border: 1px solid #e0e0e0;
}

.stat-label {
    display: block;
    font-size: 0.8em;
    color: #666;
    margin-bottom: 5px;
}

.stat-value {
    display: block;
    font-size: 1.2em;
    font-weight: 600;
    color: #1976d2;
}

.message {
    margin: 15px 0;
    padding: 15px;
    border-radius: 6px;
    border-left: 3px solid #ddd;
}

.user-message {
    background: #f8f8f8;
    border-left-color: #1976d2;
}

.assistant-message {
    background: #ffffff;
    border-left-color: #9b59b6;
}

.tool-result-message {
    background: #f8f8f8;
    border-left-color: #e74c3c;
}

.custom-message {
    background: #f0f8ff;
    border-left-color: #3498db;
}

.message-header {
    display: flex;
    justify-content: space-between;
    margin-bottom: 10px;
    font-size: 0.85em;
    color: #666;
}

.message-role {
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.05em;
}

.user-message .message-role { color: #1976d2; }
.assistant-message .message-role { color: #9b59b6; }
.tool-result-message .message-role { color: #e74c3c; }
.custom-message .message-role { color: #3498db; }

.message-content {
    color: #555;
}

.message-content pre {
    background: #f0f0f0;
    padding: 10px;
    border-radius: 4px;
    overflow-x: auto;
    white-space: pre-wrap;
    word-wrap: break-word;
}

.tool-result-error {
    color: #e74c3c;
}

.tool-result-success {
    color: #2ecc71;
}

.thinking-block {
    background: #f0f0f0;
    padding: 10px;
    border-radius: 4px;
    margin: 10px 0;
    font-style: italic;
    color: #666;
}

.tool-calls {
    margin: 10px 0;
}

.tool-call code {
    background: #f0f0f0;
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 0.9em;
}

.tool-name {
    color: #9b59b6;
}

details.tool-call {
    margin: 5px 0;
    background: #f8f8f8;
    border-radius: 4px;
    border: 1px solid #e0e0e0;
    overflow: hidden;
}

details.tool-call summary {
    cursor: pointer;
    padding: 5px 10px;
    user-select: none;
}

details.tool-call summary:hover {
    background: #e8e8e8;
}

.tool-result {
    margin: 5px 0;
    padding: 8px 12px;
    border-radius: 4px;
}

.footer {
    margin-top: 30px;
    padding-top: 20px;
    border-top: 1px solid #ddd;
    text-align: center;
    color: #999;
    font-size: 0.85em;
}

code {
    font-family: 'Fira Code', 'Consolas', 'Monaco', 'Courier New', monospace;
    background: #f0f0f0;
    padding: 2px 6px;
    border-radius: 3px;
}

pre {
    font-family: 'Fira Code', 'Consolas', 'Monaco', 'Courier New', monospace;
}

a {
    color: #1976d2;
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
""",
        "body_class": "light-theme",
    }


__all__ = [
    "HtmlExportConfig",
    "export_session_to_html",
]
